---

- debug: msg="Using Kubeconfig '{{ansible_env.K8S_AUTH_KUBECONFIG}}'"

- name: Download OpenShift Clients
  include_tasks: download_clients.yml
  when: download_clients

- name: Create Workshop Users
  include_tasks: users.yml
  when: users.create

- name: Deploy OpenShift Serverless
  include_tasks: deploy_serverless.yml
  when: deploy_serverless