apiVersion: v1
baseDomain: # your base domain
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    gcp:
      # 16 vCpu 64 GB
      type: 'n1-standard-16'
      # update it to the zones you need to be available
      # gcloud compute zones list
      # zones: []
      # Default machine types gives 128GB if you need more increase
      # the PD disk size
      # osDisk:
      #   diskType: pd-ssd
      #   diskSizeGB: 375
  replicas: 1
metadata:
  name: # unique cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  gcp:
    projectID: # your gcp project id
    region: # gcloud compute regions list
pullSecret: '{"auths":{"fake":{"auth":"bar"}}}'
# Optional
# sshKey: # update your ssh key
