---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: che-workspaces
  namespace: che
spec:
  targetNamespaces:
    - che
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  namespace: che
spec:
  channel: stable
  name: eclipse-che
  source: openshift-marketplace
  sourceNamespace: che
