apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
    - tutorial-1
    - tutorial-2
    - tutorial-3
    - tutorial-4
    - tutorial-5
    - tutorial-6
    - tutorial-7
    - tutorial-8
    - tutorial-9
    - tutorial-10
    - tutorial-11
    - tutorial-12
    - tutorial-13
    - tutorial-14
    - tutorial-15
    - tutorial-16
    - tutorial-17
    - tutorial-18
    - tutorial-19
    - tutorial-20
    - tutorial-21
    - tutorial-22
    - tutorial-23
    - tutorial-24
    - tutorial-25
    - tutorial-26
    - tutorial-27
    - tutorial-28
    - tutorial-29
    - tutorial-30
    - tutorial-31
    - tutorial-32
    - tutorial-33
    - tutorial-34
    - tutorial-35
    - tutorial-36
    - tutorial-37
    - tutorial-38
    - tutorial-39
    - tutorial-40
    - tutorial-41
    - tutorial-42
    - tutorial-43
    - tutorial-44
    - tutorial-45
    - tutorial-46
    - tutorial-47
    - tutorial-49
    - tutorial-50
